### ISSUE TITLE
Issue generating types for cw-nfts 

### ISSUE THREAD

**Issue by jhernandezb** [srdtrk/go-codegen#26]
When I try generating types for the latest main branch of [cw-nfts ](https://github.com/CosmWasm/cw-nfts/blob/main/contracts/cw721-base/schema/cw721-base.json) I get this error `panic: response get_withdraw_address is not supported, please create an issue in https://github.com/srdtrk/go-codegen`

```
      {
        "type": "object",
        "required": ["get_withdraw_address"],
        "properties": {
          "get_withdraw_address": {
            "type": "object",
            "additionalProperties": false
          }
        },
        "additionalProperties": false
      }
```

**Comment by jhernandezb** [comment]
Tested it with latest main branch is working now! thank you!

**Comment by srdtrk** [comment]
No problem!
