### ISSUE TITLE
Change '--contract-name' to '--package' and '-p'

### ISSUE THREAD

**Issue by srdtrk** [srdtrk/go-codegen#81]
In `go-codegen interchaintest add-contract`, you set a custom package name using '--contract-name'. I think this is not descriptive.

**Comment by mahiro72** [comment]
Hello @srdtrk , I'm interested in working on this issue. Would it be okay for me to pick it up?

**Comment by srdtrk** [comment]
Yes sounds good @mahiro72. Can you also keep `--contract-name` working as well? This is because I'm not planning to release 0.3 anytime soon, so I don't want to break the API, nor do I want to separate v0.2.x into a release branch.

**Comment by mahiro72** [comment]
@srdtrk 
Ok, sure! The existing `--contract-name` option will continue to work, and I will introduce the `--package` option.

**Comment by mahiro72** [comment]
@srdtrk 
While working on the implementation, I noticed that the flag name `--contract-name` seems appropriate based on the description: "Name of the contract to be added to the test suite. If not provided, the contract name will be inferred from the schema file."

Could you please double check if renaming it to `--package` is necessary? Thanks  for your consideration

**Comment by srdtrk** [comment]
Hmm, right now, what it actually does is that it determines the package name found [here](https://github.com/srdtrk/go-codegen/blob/075a705e56fbd6a975c83f0f3ca0ad07f95578a2/templates/interchaintestv8/types/files/types/%7B%7BcontractName%7D%7D/contract.go.plush#L1). And it ends up creating packages like [this](https://github.com/srdtrk/cw-ica-controller/tree/main/e2e/interchaintestv8/types/cwicacontroller).

So I think the description of the flag should also change. What do you think @mahiro72 ?

**Comment by mahiro72** [comment]
@srdtrk 
You're right, I believe introducing the --package option and updating the flag description is the good approach moving forward. Thank you for talking the time to review and provide feedback!

**Comment by srdtrk** [comment]
Great. You can also make `--contract-name` a hidden flag, cobra should already support that 😃
